post: nv12-vkms
Grillo-0/blog pull request #6
Opened 2023-06-05 17:52 UTC by Grillo-0

closes #5

2023-06-05 22:56 UTC, tales-aparecida commented
Might be relevant as an additional reference: https://docs.kernel.org/userspace-api/media/v4l/pixfmt-yuv-planar.html

2023-06-05 23:25 UTC, tales-aparecida requested changes
I don't know much about this, let's wait for more reviewers

2023-06-05 23:25 UTC, tales-aparecida commented on _posts/2023-06-03-nv12-vkms.md
> +This work proposed by my mentor [Maira Canal][maira] is going more difficult than I
```suggestion
This work proposed by my mentor [Maíra Canal][maira] is going more difficult than I
```

2023-06-05 23:25 UTC, tales-aparecida commented on _posts/2023-06-03-nv12-vkms.md
> +The TPG code was changed to use the [`drm_fixed.h`][drm_fixed] operations, as to
```suggestion
The TPG code was changed to use the [`drm_fixed.h`][drm_fixed] operations, to
```

2023-06-05 23:25 UTC, tales-aparecida commented on _posts/2023-06-03-nv12-vkms.md
> +It image representation is a pretty cube :).
```suggestion
Its visual representation is a pretty cube :).

```

2023-06-16 13:32 UTC, andrealmeid commented on _posts/2023-06-03-nv12-vkms.md
> +monitor. This technique is useful for CI/CD for example.
```suggestion
monitor. Virtual drivers are useful for automated testing.
```

2023-06-16 13:37 UTC, andrealmeid commented on _posts/2023-06-03-nv12-vkms.md
> +The conversion code was taken from the [`tpg-core.c`][tpg-core.c], a virtual
this hyperlink seems broken

2023-06-16 13:39 UTC, andrealmeid commented
- I think I would appreciate a small introduction about the post before jumping directly to "what's vkms, what's NV12"
- There's a public domain image that helps illustrating YUV https://en.wikipedia.org/wiki/YUV#/media/File:Barn-yuv.png

2023-06-19 13:36 UTC, andrealmeid commented
@Grillo-0 LGTM!

2023-06-19 13:40 UTC, tales-aparecida commented
if it LGT andrealmeid, it LGTM as well. ;D

2023-06-19 13:41 UTC, tales-aparecida approved these changes

2023-06-19 20:23 UTC, merged