post: gsoc-final-report
Grillo-0/blog pull request #7
Opened 2023-08-16 21:07 UTC by Grillo-0

2023-08-22 12:33 UTC, tales-aparecida requested changes
Um round de grammarly.com

2023-08-22 12:33 UTC, tales-aparecida commented on _posts/2023-08-13-gsoc-2023-final-report.md
> +more experience in open-source development than I could ever imagine
```suggestion
more experience, in open-source development than I could ever imagine
```

2023-08-22 12:33 UTC, tales-aparecida commented on _posts/2023-08-13-gsoc-2023-final-report.md
> +stopped working on the VKMS, so a submitted a patch to fix that.
```suggestion
stop working on the VKMS, so a submitted a patch to fix that.
```

2023-08-22 12:33 UTC, tales-aparecida commented on _posts/2023-08-13-gsoc-2023-final-report.md
> +Moreover, I use a thunderbird addon to make the diff properly
```suggestion
Moreover, I use a Thunderbird addon to make the diff properly
```

2023-08-22 12:33 UTC, tales-aparecida commented on _posts/2023-08-13-gsoc-2023-final-report.md
> +highlyted. Whwn I was thinkering with configuration, I noticed that
```suggestion
highlighted. When I was tinkering with the configuration, I noticed that
```

2023-08-22 12:33 UTC, tales-aparecida commented on _posts/2023-08-13-gsoc-2023-final-report.md
> +the CSS of the coniuguration menu was wrong, so it made the use
```suggestion
the CSS of the configuration menu was wrong, so it made the user
```

2023-08-22 12:33 UTC, tales-aparecida commented on _posts/2023-08-13-gsoc-2023-final-report.md
> +that to the the mainteiner of the addon, this patch generated a
```suggestion
that to the maintainer of the addon, this patch generated a
```

2023-08-22 12:33 UTC, tales-aparecida commented on _posts/2023-08-13-gsoc-2023-final-report.md
> +discussion that made a hole change of the CSS file due to thunderbird
```suggestion
discussion that made a whole change in the CSS file due to Thunderbird
```

2023-08-22 12:33 UTC, tales-aparecida commented on _posts/2023-08-13-gsoc-2023-final-report.md
> +Moreover, I thank the X.Org foundation for allowing me to participate
```suggestion
Moreover, I thank the X.Org Foundation for allowing me to participate
```

2023-08-24 19:40 UTC, andrealmeid commented on _posts/2023-08-13-gsoc-2023-final-report.md
> +more experience, in open-source development than I could ever imagine
```suggestion
more experience in open-source development than I could ever imagine
```

2023-08-24 19:40 UTC, andrealmeid commented on _posts/2023-08-13-gsoc-2023-final-report.md
> +Prior to GSoC, I was not accustomed to regularly submitting patches to
```suggestion
Prior to GSoC, I was not used to regularly submitting patches to
```

2023-08-24 19:41 UTC, andrealmeid commented on _posts/2023-08-13-gsoc-2023-final-report.md
> +Prior to GSoC, I was not accustomed to regularly submitting patches to
```suggestion
Prior to GSoC, I was not accustomed to regularly submit patches to
```

2023-08-24 19:41 UTC, andrealmeid commented on _posts/2023-08-13-gsoc-2023-final-report.md
> +the mailing lists. Now, I've sent many patches and revisions.  I think
```suggestion
the mailing lists. Now, I've sent many patches and revisions.  I believe
```

2023-08-24 19:42 UTC, andrealmeid commented on _posts/2023-08-13-gsoc-2023-final-report.md
> +The main goal was to increase the code coverage on the DRM core helper
```suggestion
The main goal of the project was to increase the code coverage on the DRM core helper
```

2023-08-24 19:58 UTC, andrealmeid commented on _posts/2023-08-13-gsoc-2023-final-report.md
> +# What is Left
```suggestion
# What is left to do 
```

2023-08-27 21:13 UTC, merged